In [ ]:
import open3d as O3d

ModuleNotFoundError: No module named 'open3d'

加载并显示面obj模型

In [16]:
def o3dmesh(path=''):
    simple_mesh_path = '../3D-models/rm2020_simple.obj'
    complex_mesh_path = '../3D-models/rm2022.obj'
    if path != simple_mesh_path and path != complex_mesh_path:
        print('invaild path')
    else:
        print('loading')
        mesh = O3d.io.read_triangle_mesh(path)
        mesh.compute_vertex_normals()
        O3d.visualization.RenderOption.show_coordinate_frame = True
        O3d.visualization.draw_geometries([mesh], window_name="mesh",width=1280,height=720)

def show3d():
    print('0 for simple mesh, 1 for complex mesh')
    mode = input()
    if mode == '0':
        o3dmesh('../3D-models/rm2020_simple.obj')
    elif mode == '1':
        o3dmesh('../3D-models/rm2022.obj')
    else:
        print('invaild input')

show3d()

0 for simple mesh, 1 for complex mesh
loading
[Open3D WARNING] Unable to load file ../3D-models/rm2020_simple.obj with ASSIMP


In [17]:
def o3dpcd():
    simple_pcd_path = '../3D-models/rm2020_simple.pcd'
    complex_pcd_path = '../3D-models/rm2022.pcd'
    o3d = O3d
    pcd = o3d.io.read_point_cloud(complex_pcd_path)
    o3d.visualization.draw_geometries([pcd], window_name="Open3D",width=1280,height=720)
o3dpcd()

[Open3D WARNING] Read PCD failed: unable to open file: ../3D-models/rm2022.pcd


In [ ]:
def o3dpcd():
    complex_pcd_path = '../3D-models/terra_pcd/cloudAB.pcd'
    o3d = O3d
    pcd = o3d.io.read_point_cloud(complex_pcd_path)
    print(pcd.points)
    o3d.visualization.draw_geometries([pcd], window_name="Open3D",width=1280,height=720)
o3dpcd()

In [2]:
import cv2
import numpy as np

In [4]:
cv2.Rodrigues(np.array([0, 0, 0], dtype=np.float64))

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[ 0.,  0.,  0.,  0.,  0., -1.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]]))

In [5]:
# -*- coding: UTF-8 -*-
import os
import cv2
import numpy as np
T = np.zeros((1,3), np.float32)
a = np.array((0.2,0.4,0.8), dtype=np.float64)
print (a)
R = cv2.Rodrigues(a)
print (R[0])
v3 = np.array((R[0][2,1],R[0][0,2],R[0][1,0]), dtype=np.float64)
print (v3)
c = cv2.Rodrigues(v3)
print (c[0])
b = cv2.Rodrigues(R[0])
print (b[0])
p = np.array((-2.100418,-2.167796,0.27330), dtype=np.float64)
print(cv2.Rodrigues(p))

[0.2 0.4 0.8]
[[ 0.62722765 -0.65533377  0.42085997]
 [ 0.72988824  0.6831435  -0.02404381]
 [-0.27175103  0.32226169  0.90680691]]
[0.32226169 0.42085997 0.72988824]
[[ 0.6684942  -0.57151382  0.47590699]
 [ 0.69818994  0.70271165 -0.13684712]
 [-0.25621536  0.42375498  0.86878387]]
[[0.2]
 [0.4]
 [0.8]]
(array([[-0.03625267,  0.978366  , -0.2036804 ],
       [ 0.99830522,  0.02617032, -0.05197887],
       [-0.04552397, -0.20521958, -0.97765663]]), array([[-0.43407701, -0.12092655, -0.50360256,  0.00785182,  0.50390595,
         0.40450851,  0.51785821, -0.51224665,  0.08341178],
       [ 0.49308319, -0.09508635, -0.54450423,  0.03782301, -0.42101426,
         0.51445585,  0.4367661 , -0.50700492,  0.08608749],
       [-0.06216435, -0.08196957, -0.38267115, -0.02576857, -0.06556671,
        -0.52792225, -0.51558052, -0.39914388,  0.10779185]]))


In [7]:
R[0]

array([[ 0.62722765, -0.65533377,  0.42085997],
       [ 0.72988824,  0.6831435 , -0.02404381],
       [-0.27175103,  0.32226169,  0.90680691]])

In [8]:
def rodrigues_rotation(r, theta):
    # n旋转轴[3x1]
    # theta为旋转角度
    # 旋转是过原点的，n是旋转轴
    r = np.array(r).reshape(3, 1)
    rx, ry, rz = r[:, 0]
    M = np.array([
        [0, -rz, ry],
        [rz, 0, -rx],
        [-ry, rx, 0]
    ])
    R = np.eye(4)
    R[:3, :3] = np.cos(theta) * np.eye(3) +        \
                (1 - np.cos(theta)) * r @ r.T +    \
                np.sin(theta) * M
    return R

rodrigues_rotation([0, 0, 1], 30 / 180 * np.pi)


array([[ 0.8660254, -0.5      ,  0.       ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [9]:
import math

In [10]:
rodrigues_rotation([0, 0, 1], math.radians(30))

array([[ 0.8660254, -0.5      ,  0.       ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [12]:
import numpy as np
import cv2
from math import radians

def CV2RM(points_3d):
    x, y, z = points_3d
    return [-z, -x, y]

class Maper:
    def __init__(self, camera_x = -4.8, camera_y = 3.8, camera_z = 1.2, r_x = 20) -> None:
        # 相机外参
        self.camera_pos = np.array([camera_x, camera_y, camera_z], dtype=np.float32)
        self.camera_dir = np.array([radians(r_x), radians(0), radians(0)], dtype=np.float32)

        # 焦距与传感器尺寸
        self.focal_length = 6
        self.sensor_size_x = 7.176 # 1/1.8 inch
        self.sensor_size_y = 5.32

        self.mapper = []

    def get_points_map(self, image = np.zeros((1600, 1200, 3), dtype=np.uint8)):
        # 场地点云
        x = 0
        z = 0
        points_3d = []
        x_len = int(13.879 // 0.2) + 1
        z_len = int(25.879 // 0.2) + 1
        print("x_len:",x_len, " z_len:", z_len)
        i = 0
        j = 0
        while x < 13.879:
            j = 0
            while z < 25.879:
                points_3d.append([x, 0, z])
                z += 0.2
                j += 1
            x += 0.2
            z = 0
            i += 1
        # print("i:",i, "j:", j)
        # print("len(points_3d):", len(points_3d))
        self.reshape_points_3d = np.reshape(points_3d, (x_len, z_len, 3))
        # print("reshape_points_3d.shape:", self.reshape_points_3d.shape, " points_3d.shape:", np.array(points_3d).shape)

        points_3d = np.array(points_3d, dtype=np.float32)
        self.points_3d = points_3d.copy()

        # 图像尺寸
        image_width = image.shape[1]
        image_height = image.shape[0]

        fx = self.focal_length * image_width / self.sensor_size_x
        fy = self.focal_length * image_height / self.sensor_size_y
        cx = image_width / 2
        cy = image_height / 2
        # 
        K = np.array([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], dtype=np.float32)

        # 计算被旋转后的平移向量
        R, _ = cv2.Rodrigues(self.camera_dir) 
        # R 叉乘 camera_pos
        tvec = R @ self.camera_pos      
        # rvec, _ = cv2.Rodrigues(R) 

        points_2d, _ = cv2.projectPoints(points_3d, self.camera_dir, tvec, K, None)
        self.points_2d = np.array(points_2d, dtype=np.int32)
        
        self.reshape_points_2d = np.reshape(points_2d, (x_len * z_len, 2))
        # print("points_2d.shape:", points_2d.shape, " reshape_points_2d.shape:", self.reshape_points_2d.shape)
        maper_points = list(zip(self.points_3d, self.reshape_points_2d))
        self.maper_points = maper_points
        return maper_points



    def draw_points_2d(self, image = np.zeros((1600, 1200, 3))):
        cv2.namedWindow("image", cv2.WINDOW_NORMAL)
        for p in self.points_2d:
            p = np.array(p[0], dtype=np.int32)
            cv2.circle(image, p, 5, (0, 255, 0), -1) 

        cv2.imshow("image", image)
        if ord('b') == cv2.waitKey(1):
            cv2.destroyAllWindows()
            exit(0)

    def demo_display(self, image = np.zeros((1600, 1200, 3))):
        cv2.namedWindow("image", cv2.WINDOW_NORMAL)
        for p in self.points_2d:
            p = np.array(p[0], dtype=np.int32)
            cv2.circle(image, p, 5, (0, 255, 0), -1) 

        cv2.imshow("image", image)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

    def demo_display_slow(self, image = np.zeros((1600, 1200, 3))):
        cv2.namedWindow("image", cv2.WINDOW_NORMAL)
        for x in self.reshape_points_2d:
            for p in x:
                p = np.array(p[0], dtype=np.int32)
                cv2.circle(image, p, 5, (0, 255, 0), -1) 
                
                cv2.imshow("image", image)
                if ord('b') == cv2.waitKey(1):
                    cv2.destroyAllWindows()
                    exit(0)
            break

if __name__ == "__main__":
    maper = Maper()
    maper.get_points_map()
    reshape_points_2d = maper.reshape_points_2d
    maper.demo_display()
    # maper.demo_display_slow()

x_len: 70  z_len: 130


找X

In [2]:
x = [i[0][0][0] for i in np.array(reshape_points_2d, dtype=np.int32)]
print(x) 

[-1384, -1301, -1218, -1136, -1053, -970, -888, -805, -722, -640, -557, -474, -392, -309, -226, -144, -61, 21, 103, 186, 269, 351, 434, 517, 600, 682, 765, 848, 930, 1013, 1096, 1178, 1261, 1344, 1426, 1509, 1592, 1674, 1757, 1840, 1922, 2005, 2088, 2170, 2253, 2336, 2418, 2501, 2584, 2666, 2749, 2832, 2914, 2997, 3080, 3162, 3245, 3328, 3410, 3493, 3576, 3658, 3741, 3824, 3906, 3989, 4072, 4154, 4237, 4320]


找Y

In [13]:
y = [i[0][1] for i in np.array(reshape_points_2d, dtype=np.int32)[0]]
# print("len(y)", len(y))

In [15]:
points_2d = np.reshape(maper.points_2d, (len(maper.points_2d), 2))

: 

In [8]:
points_3d = maper.points_3d

In [13]:
maper_points = maper.maper_points